### ISSUE TITLE
Add package to brew 

### ISSUE THREAD

**Issue by bvc3at** [soldiermoth/hlsq#1]
Hello! Thank you for awesome tool! What do you think about adding hlsq installable via [homebrew](https://brew.sh) (macOS package manager)? You could do it by creating [tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) or pushing package directly in brew (cask/core) formula list

**Comment by soldiermoth** [comment]
That's a good idea, I'll look into doing that

**Comment by soldiermoth** [comment]
This should be available with homebrew now
```
brew install soldiermoth/tap/hlsq
```
